/** @returns {import('./types.js').AppState} */
export function createState() {
  return {
    tool: 'select',
    fill: '#00e5ff',
    stroke: '#ffffff',
    strokeW: 2,
    opacity: 100,
    fillMode: 'solid',
    shape: 'rect',
    sides: 6,
    objects: [],
    selected: [],
    history: [],
    histIdx: -1,
    zoom: 1,
    panX: 50,
    panY: 40,
    canvasW: 800,
    canvasH: 600,
    penPoints: [],
    penEl: null,
    polyPoints: [],
    polyEl: null,
    draggingHandle: null,
    pencilPts: [],
    pencilEl: null,
    tubePts: [],
    tubeEl: null,
    strokeMeshMode: 'flat',
    shapeStart: null,
    shapePreview: null,
    selDragStart: null,
    selDragOffset: null,
    nodeHandles: [],
    drag3: false,
    pan3: false,
    lm3: {},
    three: { rotating: true },
    activeScreen: '2d',
    realtime3d: true,
    viewMode3d: 'solid',
  };
}
