/** @returns {import('./types.js').AppState} */
export function createState() {
  return {
    tool: 'select',
    fill: '#ff6b35',
    stroke: '#ffffff',
    bg2d: '#f8f9fc',
    bg3d: '#111318',
    strokeW: 2,
    opacity: 100,
    fillMode: 'solid',
    shape: 'roundsquare',
    sides: 6,
    objects: [],
    selected: [],
    history: [],
    histIdx: -1,
    zoom: 1,
    panX: 50,
    panY: 40,
    canvasW: 800,
    canvasH: 600,
    penPoints: [],
    penEl: null,
    polyPoints: [],
    polyEl: null,
    draggingHandle: null,
    pencilPts: [],
    pencilEl: null,
    freehandAutoClose: true,
    tubePts: [],
    tubeEl: null,
    strokeMeshMode: 'flat',
    documentD3: null,
    documentStyle: null,
    shapeStart: null,
    shapePreview: null,
    selDragStart: null,
    selDragOffset: null,
    nodeHandles: [],
    drag3: false,
    pan3: false,
    lm3: {},
    threePointerDown: null,
    threePointerMoved: 0,
    threeObjectDrag: null,
    three: { rotating: true },
    activeScreen: '2d',
    splitRatio: 0.5,
    realtime3d: true,
    gizmoMode: 'translate',
    viewMode3d: 'solid-loops',
    clipboard: null,
    clipboardPasteCount: 0,
  };
}
